[tool.black]
line-length = 79
target-version = ["py39"]
include_trailing_comma = true
extend-exclude = '''
  docs
'''

[tool.isort]
py_version=39
line_length = 79
profile = "black"
extend_skip_glob = ["docs/*"]